### ISSUE TITLE
Slow requests

### ISSUE THREAD

**Issue by crackcomm** [ipfs/go-ipfs-api#104]
When [DisableKeepAlives](https://github.com/ipfs/go-ipfs-api/blob/master/shell.go#L66) is true simple block put of 32 bytes takes 1 second.

**Comment by Stebalien** [comment]
Depends on https://github.com/ipfs/go-ipfs/issues/5168.

**Comment by Stebalien** [comment]
That may also be automatic providing. See: https://github.com/ipfs/go-ipfs/pull/4333

**Comment by aschmahmann** [comment]
Is this still an issue?

**Comment by crackcomm** [comment]
@aschmahmann if I remember correctly it wasn't exactly the issue in the client but on the server.

**Comment by aschmahmann** [comment]
@crackcomm thanks for the speedy response! I tried doing a simple block put with the default local shell (that has `DisableKeepAlives=true`) and it seemed pretty fast (around 10 milliseconds), so I'm going to mark this as closed.
