### ISSUE TITLE
PubSubPublish returns a non-nil error wraps a nil error.

### ISSUE THREAD

**Issue by chaintechlab** [ipfs/go-ipfs-api#117]
func (s *Shell) PubSubPublish(topic, data string) (err error) {
    resp, err := s.Request("pubsub/pub", topic, data).Send(context.Background())
    if err != nil {
        return err
    }
    defer resp.Close()
   + if resp.Error == nil {
   +    return nil
   +  }
    return resp.Error
}

Without adding the three lines shown above, this function will return a non-nil error with wraps a nil resp.Error. The reason is that the error interface includes a nil is not nil itself. https://golang.org/doc/faq#nil_error

**Comment by Stebalien** [comment]
Dammit! This is the *second* one of those I put into that PR.
