### ISSUE TITLE
Requesting Simple Examples on Main Page

### ISSUE THREAD

**Issue by patientplatypus** [ipfs/go-ipfs-api#120]
Ok - I have to admit I'm totally lost. 

What I would like to do is seemingly trivial - I have a go application inside a docker container and I would like the ability to add messages to ipfs, store the hash for later retrieval, and later retrieve them. Here are all the resources I've looked into to try and figure out how to solve this problem: 

https://discuss.ipfs.io/ - Lots of dead threads and general discussion/nontechnical.

https://docs.ipfs.io/introduction/usage/ Great examples! Except it all works from the command line.

https://ipfs.io/blog/1-run-ipfs-on-docker/ - This is closer, however with caveats. Written a couple years ago, not 100% certain it is still relevant. Also, it all works by execing into Docker. Finally, it appears to work with the http curl commands, and not a go hook.

https://github.com/gnosis/pm-trading-db - I guess I could try and back out what these guys did, but it looks complicated.

Does anyone have any advice?

**Comment by Stebalien** [comment]
There's an example here: https://github.com/ipfs/go-ipfs-api/blob/master/tests/main.go. But you're right, we need a simple one in the readme.
