### ISSUE TITLE
issue regarding function

### ISSUE THREAD

**Issue by akshitababel** [ipfs/go-ipfs-api#122]
Can I create app ID using go ipfs api? Is there any function to do this? If not can we have a function included in go ipfs api to create app id?

**Comment by kggp1995** [comment]
@akshitababel , are you checking for an API function to support what the command `ipfs name publish --key=<app_name>` does? 

AFAIK, There's just the function to spwan/link a shell to an IPNS entry. I don't think there's one to create a new IPNS entry.

@whyrusleeping , care to comment or drop suggestions on this?
Others are also welcome. TIA!

**Comment by Stebalien** [comment]
What do you mean by "app ID"?

**Comment by akshitababel** [comment]
The key which we use to run `ipfs name --key=<app_name>` . That key is the app ID.

**Comment by Stebalien** [comment]
Got it (FYI, that's not really an app ID; it's just a key).

There's no pre-defined function but you can manually fire off a request (patches welcome):

```go
func newKey(ctx context.Context, name string) (string, error) {
	var newKey struct {
		Name string
		Id   string
	}

	if err := s.
		Request("key/gen").
		Arguments(name).
		Option("type", "rsa").
		Exec(context.Background(), &newKey); err != nil {
		return err
	}
	return newKey.Id
}
```

That should work (untested).

**Comment by Stebalien** [comment]
I filed a feature request: https://github.com/ipfs/go-ipfs-api/issues/124

**Comment by akshitababel** [comment]
Thanks for reverting back.
I am getting the following error when i am trying to use the code you suggested: 
key/gen: please specify a key size with --size

**Comment by akshitababel** [comment]
This code needs one more parameter which is the size of the key. The above code needs to get updated with the following one:

func newKey(ctx context.Context, name string) (string, error) {
	var newKey struct {
		Name string
		Id   string
	}
	var err error
	s := shell.NewLocalShell()
	if err := s.
		Request("key/gen").
		Arguments(name).
		Option("type", "rsa").Option("size", "2048").
		Exec(context.Background(), &newKey); err != nil {
		fmt.Println(err)
		return "", err
	}
	return newKey.Id, err
}

**Comment by Stebalien** [comment]
Yes. However, my bandwidth is a bit limited so the review cycle may be a bit long.
