### ISSUE TITLE
trying to pull range requests with IPFS client code

### ISSUE THREAD

**Issue by rfielding** [ipfs/go-ipfs-api#131]
I copied some patterns I saw in this library, and thought that this must be the way to do it.

I get a request, and set Range on the header.  I call an almost identical provider that wraps S3, and range request in this format works.  I should get the file seeked up to `lo`.  Is this supposed to work with IPFS?

```go
	req := r.Shell.Request("cat", string(n))
	req.Header("Range", fmt.Sprintf("bytes=%d-%d", lo, hi))
	res, err := req.Send(context.Background())
```

Also, when pulling huge media, client disconnects are very common.  Browsers will pull the first 100k or so of a video just to figure out what it is, and cut off the connection.  So, client disconnects are not logged as errors, because if the server yields a 200 or a 206, it is doing its end of the contract and sending bytes back.  It's not required that the client consume all the bytes.

```

```00:56:22.025 ERROR  cmds/http: write tcp4 127.0.0.1:5001->127.0.0.1:54520: write: connection reset by peer responseemitter.go:132
00:56:22.082 ERROR  cmds/http: write tcp4 127.0.0.1:5001->127.0.0.1:54522: write: broken pipe responseemitter.go:132
00:57:02.216 ERROR  cmds/http: write tcp4 127.0.0.1:5001->127.0.0.1:54554: write: connection reset by peer responseemitter.go:132
01:08:50.813 ERROR  cmds/http: write tcp4 127.0.0.1:5001->127.0.0.1:55984: write: connection reset by peer responseemitter.go:132
01:09:44.471 ERROR  cmds/http: write tcp4 127.0.0.1:5001->127.0.0.1:56008: write: connection reset by peer responseemitter.go:132

**Comment by magik6k** [comment]
So we don't support the range header in the HTTP API, but:
* The `cat` command has 2 options for this - `offset` and `length` (see `ipfs cat --help`)
* We do support range header on the gateway (by default on `127.0.0.1:8080/[ipfs/ipns]`)
* When [coreapi](https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/interface/unixfs.go#L38) http client happens, you'll get a file implementing `io.Seeker` from `api.Unixfs().Get`, and the whole thing sholud be smarter in general, but that's the future.

**Comment by Stebalien** [comment]
It's happening: https://github.com/ipfs/go-ipfs-http-client.
