### ISSUE TITLE
Using HTTPS transport

### ISSUE THREAD

**Issue by CrackHD** [ipfs/go-ipfs-api#134]
What is the option to use TLS-driven IPFS node?
For example, Infura gives node `https://ipfs.infura.io:5001/`;

```
func NewShell(url string) *Shell {
	c := &gohttp.Client{
		Transport: &gohttp.Transport{
			Proxy:             gohttp.ProxyFromEnvironment,
			DisableKeepAlives: true,
		},
	}

	return NewShellWithClient(url, c)
}
```

Any suggestions?

**Comment by Stebalien** [comment]
Does `NewShell("https://ipfs.infura.io:5001")` not work? It should support HTTPs. If not, what errors are you getting?

**Comment by CrackHD** [comment]
No.I don't see a reason why it should work if it is currently clearly says in source HTTP will be used. 

The node, when hit over 80 port instead of 443 by `NewShell()`, replies with dummy error message and i see it in error text in go program:

`"infura.io:5001"` =>
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

`NewShell("https://ipfs.infura.io:5001/"` =>
```
panic: add: multipart: NextPart: EOF

goroutine 1 [running]:
main.initializeIPFS()
        ...go:99 +0x286
main.init.0()
        ...go:26 +0x25
make: *** [run] Error 2

```

Code:
```go
ipfs := shell.NewShell(addr) // https://..
cid, err = ipfs.Add(strings.NewReader("hello world!"))
		if err != nil {
			panic(err)
                }
```

**Comment by Stebalien** [comment]
> No.I don't see a reason why it should work if it is currently clearly says in source HTTP will be used.

Where does it say this? The default `http.Transport` supports HTTPS When you run `curl https://ipfs.infura.io:5001/api/v0/versoin` on the same machine, what do you get?

This *does* work. You can, e.g., try `NewShell("https://ipfs.io").Version()`

**Comment by CrackHD** [comment]
> When you run curl https://ipfs.infura.io:5001/api/v0/versoin on the same machine, what do you get?

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Maybe i was just wrong about Infura public node capabilities. It looks like, according to comment on issue https://github.com/INFURA/infura/issues/45#issuecomment-396428309, they doesn't support part of API.

**Comment by Stebalien** [comment]
> To Readme/howto, add

I'd rather have a comment stating all possible forms but yes, we should (patches welcome).

> The issue is still unresolved since i don't understand what's wrong with Infura IPFS API.

You may need to somehow authenticate. We're not associated with Infura so there's not much we can do to help debug this.

**Comment by hiddentao** [comment]
Having this same issue. The URL above was misspelt. When I run: `curl https://ipfs.infura.io:5001/api/v0/version` I get:

```
{"Version":"0.4.22","Commit":"c6489e5bc","Repo":"7","System":"amd64/linux","Golang":"go1.12.13"}
```

**Comment by hiddentao** [comment]
Ok, got it working. No authentication is required with Infura. Just ensure your connection settings are correct. I'm using a Node package -> https://www.npmjs.com/package/ipfs-http-client. My code is like this:

```
const ipfsClient = require('ipfs-http-client')

const ipfs = ipfsClient({
  host: 'ipfs.infura.io',
  port: '5001',
  protocol: 'https',
})

ipfs.add(/* ... */)
```
