### ISSUE TITLE
proposed Module rename. -api => -http-client

### ISSUE THREAD

**Issue by daviddias** [ipfs/go-ipfs-api#139]
Opening for tracking purposes. @Stebalien already commented at https://github.com/ipfs/ipfs/issues/374

**Comment by adamgall** [comment]
@daviddias can you fix that link?

**Comment by Stebalien** [comment]
(note: the plan is to do this along with the CoreAPI rewrite so we don't break existing users)

**Comment by Stebalien** [comment]
IMO, yes.

**Comment by willscott** [comment]
@Stebalien - sounds like https://github.com/ipfs/go-ipfs-http-client should now generally be the default choice over this one, so this issue is probably as resolved as it ever will be.
