### ISSUE TITLE
Is this repository still Unofficial?

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/go-ipfs-api#147]
<img width="443" alt="screenshot 2018-12-31 at 09 33 21" src="https://user-images.githubusercontent.com/33528/50556882-25078180-0cdf-11e9-8719-efeb6ddc696a.png">

Is this repository still "unofficial"? 😄

**Comment by Stebalien** [comment]
Not really. We're planning on deprecating this in favor of a CoreAPI based version (https://github.com/ipfs/go-ipfs-http-client) but we're not there yet.

Fixed.
