### ISSUE TITLE
How to use "shell.Request("/files/write")...."

### ISSUE THREAD

**Issue by oblivioned** [ipfs/go-ipfs-api#159]
When I tried to use the request for"/files/write", I encountered some problems. Because I just touched the ipfs-go-api, I had some doubts. For "/files/write", most of them need to input a file. Is it filled in in in the body, if the terminal command is?

`"ipfs files write -e /Path/Filename.x. / filepath/file"` 

and

`"echo 'some append dates' | ipfs files write -o = 100 /Path/Filename.x"` 

How should I use "Request" expression ?

I looked up the source code for shell. Add and generated the Body according to the same rules.

`

	fr := files.NewBytesFile(bytes.NewBufferString("SomeContentWriteTest").Bytes())

	slf := files.NewSliceDirectory([]files.DirEntry{files.FileEntry("", fr)})

	fileReader := files.NewMultiFileReader(slf, true)

	var out object

	err := shell.
		Request("/files/write").
		Arguments(name).
		Body(fileReader).
		Option("e",true).
		Exec(context.Background(), &out)`

The error message returned is "/files/write: multipart: NextPart: EOF"

How should I solve it? I hope to get your help.

Thank you !

**Comment by Stebalien** [comment]
That's a really confusing error. It turns out there are two issues here:

1. The server is trying to redirect `/api/v0//files/write` to `/api/v0/files/write`. The client can't handle this as it can't go back to the beginning of the request body. Honestly, I'm not sure why go tries.
2. That `Exec` line should be `Exec(contexts.Background(), nil)` to signal that no value is expected.

**Comment by oblivioned** [comment]
Thank you for your answer. I modified the code and succeeded in getting the result. Because it is not only new to IPFS, but also new to ‘golang’. If you want to get your answer, I guess it will take a lot of time. 

Thank you again for your reply.

`	Successful code:
	
	shell := shell.NewLocalShell()

	fr := files.NewBytesFile(bytes.NewBufferString("SomeContentWriteTest").Bytes())

	slf := files.NewSliceDirectory([]files.DirEntry{files.FileEntry("", fr)})

	fileReader := files.NewMultiFileReader(slf, true)

	err := shell.
		Request("files/write").
		Arguments(name).
		Body(fileReader).
		Option("e",true).
		Exec(context.Background(), nil)`

**Comment by Stebalien** [comment]
> Because it is not only new to IPFS, but also new to ‘golang’. 

No, this issue was just *really* confusing. It took me a few hours to figure out what was going wrong.

**Comment by hleb-albau** [comment]
@Stebalien is it possible to submit dir with 1k files using one write request and code above(by addition more **DirEntry** to **SliceDirectory**)?

**Comment by Stebalien** [comment]
Yes.

**Comment by hleb-albau** [comment]
@Stebalien I tried next code and get error **Error: files/write: /testdir/ was not a file**:
```
			ipfs := shell.NewShell("localhost:5001")
			f1 := files.NewBytesFile(bytes.NewBufferString("Test1").Bytes())
			f2 := files.NewBytesFile(bytes.NewBufferString("Test2").Bytes())
			dir := files.NewSliceDirectory([]files.DirEntry{
				files.FileEntry("1.txt", f1),
				files.FileEntry("2.txt", f2),
			})


			reader := files.NewMultiFileReader(dir, true)

			err := ipfs.
				Request("files/write").
				Arguments("/testdir/").
				Body(reader).
				Option("parents",true).
				Option("raw-leaves",true).
				Option("create",true).
				Exec(context.Background(), nil)
```
If i change arguments to **/testdir**, than only first file will be saved under **testdir** path.
What should I change?

**Comment by Stebalien** [comment]
Mind creating a new issue to discuss this?
