### ISSUE TITLE
undefined: strings.builder

### ISSUE THREAD

**Issue by obo20** [ipfs/go-ipfs-api#171]
when I run "go get -u github.com/ipfs/go-ipfs-api" I get the following problems in the console:

`../../../../../go/src/github.com/multiformats/go-multiaddr/codec.go:140:10: undefined: strings.Builder`
`../../../../../go/src/github.com/multiformats/go-multiaddr/component.go:118:8: undefined: strings.Builder`
`../../../../../go/src/github.com/multiformats/go-multiaddr/component.go:125:32: undefined: strings.Builder`

**Comment by Stebalien** [comment]
You'll need go >= 1.11
