### ISSUE TITLE
Support `wrap-with-directory` Option

### ISSUE THREAD

**Issue by channprj** [ipfs/go-ipfs-api#176]
# Example

```go
func Wrap(enabled bool) ipfs.AddOpts {
	return func(rb *ipfs.RequestBuilder) error {
		rb.Option("wrap-with-directory", enabled)
		return nil
	}
}
```

**Comment by Stebalien** [comment]
FYI, you might want to try the new https://github.com/ipfs/go-ipfs-http-client instead. It's not quite _stable_ but has more features.

**Comment by channprj** [comment]
@Stebalien Thanks. ☺️ May I ask what is the difference between `go-ipfs-api` and `go-ipfs-http-client`? Can I use the `-w` option in it?

**Comment by Stebalien** [comment]
> @Stebalien Thanks. relaxed May I ask what is different between go-ipfs-api and go-ipfs-http-client?

go-ipfs-http-client is intended to replace this library.

> Can I use the -w option?

With _this_ library, you'll have to add that option. With go-ipfs-http-client, you'd call `Unixfs().Add(ctx, files.NewMapDirectory(map[string]files.Node{"filename": files.NewReaderFile(myFile)})`.

**Comment by channprj** [comment]
@Stebalien Thank you. I'll try it ASAP. 🚀

**Comment by susarlanikhilesh** [comment]
I think someone already raised PR. I think this can be linked with the PR.

https://github.com/ipfs/go-ipfs-api/pull/294
