### ISSUE TITLE
add pin=false faile

### ISSUE THREAD

**Issue by woniuxu** [ipfs/go-ipfs-api#177]
Hi guys,
I meet an error "add: File argument 'path' is required" when sending the "add --pin=false" request.
The code is as following:

```go
func (i *IPFS) AddNopin(uploadFile io.Reader) (string, error) {
	var hash string
	err := i.sh.Request("add").Option("pin", false).Body(uploadFile).Exec(context.Background(), &hash)
	fmt.Println(err.Error())
	return hash, err
}
```

do i miss something in the request?  
thanks.

**Comment by Stebalien** [comment]
Please take a look at the existing `Add` function. You need to use `go-ipfs-files` to encode the file you're uploading.
