### ISSUE TITLE
CID v1 support

### ISSUE THREAD

**Issue by treeder** [ipfs/go-ipfs-api#185]
Does this library support the new CID format?  https://github.com/multiformats/cid

**Comment by Stebalien** [comment]
Yes.

**Comment by treeder** [comment]
How do you use it?

**Comment by Stebalien** [comment]
Ah, sorry, I misunderstood. You mean "can I add a file/directory and get a CIDv1 back?".  Hm, it looks like we don't have any options for doing that. PR: #186.
