### ISSUE TITLE
unixfs.go add files/stat

### ISSUE THREAD

**Issue by delgyd** [ipfs/go-ipfs-api#189]
type UnixStat struct{
	Hash string
	Size uint64
	Type string
	CumulativeSize uint64
	ChildBlocks uint64
}

func (s *Shell) FileStat(path string) (*UnixStat,error) {
	var o *UnixStat
	err := s.Request("files/stat",path).Exec(context.Background(),&o)
	if err != nil {
		return nil,err
	}
	return o,nil
}

**Comment by Stebalien** [comment]
Mind submitting a PR?

**Comment by delgyd** [comment]
package shell

import (
	"context"
	"fmt"
)


type UnixStat struct{
	Hash string
	Size uint64
	Type string
	CumulativeSize uint64
	ChildBlocks uint64
}

type UnixLsObj struct {
	Name string
	Hash string
	Size uint64
	Type string
}

type UnixLsRs struct {
	Info []*UnixLsObj
}

func (s *Shell) FileList(path string) (Rs UnixLsRs , err error) {
	var o map[string]interface{}
	err = s.Request("files/ls",path).Exec(context.Background(),&o)
	if err != nil {
		return Rs,err
	}
	x := o["Entries"].([]interface{})
	for _,v := range x {
		dtem := v.(map[string]interface{})
		name := dtem["Name"].(string)

		stem,serr := s.FileStat(path +"/"+ name)
		if serr != nil {
			fmt.Println(stem)
			return Rs,serr
		}
		size := stem.CumulativeSize
		typei := stem.Type
		hash := stem.Hash
		Rs.Info = append(Rs.Info,&UnixLsObj{name,hash,size,typei})

	}
	return Rs,nil
}


func (s *Shell) FileStat(path string) (*UnixStat,error) {
	var o *UnixStat
	err := s.Request("files/stat",path).Exec(context.Background(),&o)
	if err != nil {
		return nil,err
	}
	return o,err
}

**Comment by pengisgood** [comment]
@Stebalien could you please review the PR I made?

**Comment by pengisgood** [comment]
This one can be closed since I have implemented the api in `mfs.go`
