### ISSUE TITLE
Http response got EOF error with correct body occasionally

### ISSUE THREAD

**Issue by pengisgood** [ipfs/go-ipfs-api#223]
When I debug in the following [code](https://github.com/ipfs/go-ipfs-api/blob/7009904238640459874f3dff161ceb26caf458c8/request.go#L51), sometimes it can read data from the body correctly but with **EOF** error.
```
func (r *trailerReader) Read(b []byte) (int, error) {
	n, err := r.resp.Body.Read(b)
	if err != nil {
		if e := r.resp.Trailer.Get("X-Stream-Error"); e != "" {
			err = errors.New(e)
		}
	}
	return n, err
}
```
I called [this method](https://github.com/ipfs/go-ipfs-api/blob/7009904238640459874f3dff161ceb26caf458c8/mfs.go#L278) in my code:
```
// FilesRead read a file in a given MFS
func (s *Shell) FilesRead(ctx context.Context, path string, options ...FilesOpt) (io.ReadCloser, error) {
	rb := s.Request("files/read", path)
	for _, opt := range options {
		if err := opt(rb); err != nil {
			return nil, err
		}
	}

	resp, err := rb.Send(ctx)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		return nil, resp.Error
	}

	return resp.Output, nil
}
```

Any thoughts?

**Comment by Stebalien** [comment]
This is normal: https://golang.org/pkg/io/#Reader (paragraph 3).

**Comment by Stebalien** [comment]
(not that I agree with go's choices here..., but it's normal)

**Comment by pengisgood** [comment]
Thanks for the response. Yea, it's weird. 😞
