### ISSUE TITLE
Calling "go-ipfs-api" as a Library from node

### ISSUE THREAD

**Issue by janitha1989** [ipfs/go-ipfs-api#231]
I tried to create a shared object binary of go-ipfs-api using below command.

go build -o ipfsapi.so -buildmode=c-shared ipfsapi.go

Then I used the generated ipfsapi.so and ipfsapi.h within the node project as 
`var ipfsapi= ffi.Library("/home/chainbc/go/src/test/ipfsapi.so", {
  Add: ["string", ["string"]]
  }); `

But when I run it comes below run time error.

unexpected fault address 0x29a7000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x29a7000 pc=0x7f3baaee3ede]

can anyone help with this? Detail error description 
[error.txt](https://github.com/ipfs/go-ipfs-api/files/5903094/error.txt)
attached here

**Comment by Stebalien** [comment]
Hey, this issue tracker is for bugs in go-ipfs-api. Please ask support related questions on https://discuss.ipfs.io and/or stackoverflow (as this doesn't look go-ipfs specific).
