### ISSUE TITLE
Get directories count using go-ipfs

### ISSUE THREAD

**Issue by varshadqz** [ipfs/go-ipfs-api#236]
I am trying to get the directories count and their information using `go-ipfs-api`. Used the following code:

```
func main() {
        sh := shell.NewShell("localhost:5001")
        dir,err:=sh.FilesLs(context.TODO(),"")
        if err != nil {
                fmt.Fprintf(os.Stderr, "error: %s", err)
                os.Exit(1)
        }
        fmt.Printf("Dir is: %d", dir)
}
```

This returns `Dir is: [824634392256]`. Whereas, I added 2 directories using the command: `sudo ipfs add -r /home/user/ipfstest` which have files inside.  I am not getting what output it is returning? and why only one? Please guide.

**Comment by Stebalien** [comment]
`ipfs add -r /home/user/ipfstest` does not add files to `ipfs files`, it just imports the files into go-ipfs. To add them to MFS, you need to follow it up with a call to `ipfs files cp /ipfs/OutputOfIPFSAdd /name-you-want-to-use-in-mfs`.

If you have any followup questions, please raise them on discuss.ipfs.io.
