### ISSUE TITLE
AddDir creates object with no links (but only data)

### ISSUE THREAD

**Issue by kalmi** [ipfs/go-ipfs-api#24]
I assumed sh.AddDir would end up returning a hash that is usable with sh.List (ls). This appears not to be the case. I get an object like this:
`{"Links":[],"Data":"\u0008\u0002\u0012?\u0007--95a955e5bfb13034cd6b0f1d6fece94172647b39db9122b368ae146fc248\r\nContent-Disposition: file; filename=\"1_emptydir\"\r\nContent-T.......`

Is this a bug?

Code example:
https://gist.github.com/kalmi/f5c54c8261c327f6b8ed4187e2f53a02 (complete unexpected output at the bottom in a comment)

**Comment by whyrusleeping** [comment]
Very odd that the multipart response is getting mangled into that. Can we verify this is still an issue?

**Comment by mikesun** [comment]
I can verify it's still an issue.

**Comment by mikesun** [comment]
I can try and take a look at this if someone can point me in the general direction? Is it an issue with how the IPFS server API is handling the multi-part POST? Or is the issue with the the code in `AddDir()` in the client?

**Comment by whyrusleeping** [comment]
@mikesun My first guess is that its an issue with the clients AddDir or request parsing code.

**Comment by mikesun** [comment]
I got it working through modifications to `github.com/whyrusleeping/go-multipart-files`. Here's a PR, kinda hacky but working:
https://github.com/ipfs/go-ipfs-api/pull/52
