### ISSUE TITLE
use with go-ipfs/core - panic: Reuse of exported var name: utpAckSkippedResends

### ISSUE THREAD

**Issue by alexander-vielimchanitsia** [ipfs/go-ipfs-api#26]
This code:
`package main

import (
    "fmt"
    _ "github.com/ipfs/go-ipfs-api"
    _ "github.com/ipfs/go-ipfs/core"
)

func main() {
    fmt.Println("test")
}`

Getting this error:

`2016/04/14 23:54:05 Reuse of exported var name: utpAckSkippedResends
panic: Reuse of exported var name: utpAckSkippedResends

goroutine 1 [running]:
log.Panicln(0xc8200d3db0, 0x2, 0x2)
    /usr/local/go/src/log/log.go:334 +0xc1
expvar.Publish(0x5d39e0, 0x14, 0x20045c8, 0xc820073b10)
    /usr/local/go/src/expvar/expvar.go:254 +0x233
expvar.NewInt(0x5d39e0, 0x14, 0xb)
    /usr/local/go/src/expvar/expvar.go:272 +0x75
gx/ipfs/QmadkZhaLw1AhXKyBiPmydRuTexhj6WkiZPpo5Uks6WUVq/utp.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmadkZhaLw1AhXKyBiPmydRuTexhj6WkiZPpo5Uks6WUVq/utp/utp.go:52 +0x97
gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net/utp.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net/utp/utp_util.go:105 +0x45
gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net/net.go:298 +0x56
gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/net/conn.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/net/conn/secure_conn.go:124 +0x60
gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/net.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/net/interface.go:155 +0x40
gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/host.init()
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/QmccGfZs3rzku8Bv6sTPH3bMUKD1EVod8srgRjt5csdmva/go-libp2p/p2p/host/host.go:64 +0x5b
github.com/ipfs/go-ipfs/core.init()
    /Users/alexandervielimchanitsia/go/src/github.com/ipfs/go-ipfs/core/pathresolver.go:91 +0x6a
main.init()
    /Users/alexandervielimchanitsia/Documents/xxx/xxx/service/host.go:11 +0x45

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 21 [select]:
gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.(*MirrorWriter).logRoutine(0xc82006e940)
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:71 +0x33c
created by gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.NewMirrorWriter
    /Users/alexandervielimchanitsia/go/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:38 +0xe2`

**Comment by whyrusleeping** [comment]
Hrm... this is likely because go-ipfs-api and ipfs/core import different versions (indirectly) of the utp package.

While this does really suck (I ran into it a couple times too) do you need both go-ipfs-api and core? the api is for controlling an existing node, and core is generally used for instantiating a new node in process.

**Comment by alexander-vielimchanitsia** [comment]
>Hrm... this is likely because go-ipfs-api and ipfs/core import different versions (indirectly) of the utp package.
I did updated specially yesterday but did not help :(

>do you need both go-ipfs-api and core?
Yes, because me need save objects to a ipfs daemon from my custom ipfs server.

So, this worked early, when i used fork your go-ipfs-api and added there ObjectGet and ObjectPut methods, because they were not in the original repo, but now i  saw updated :)

**Comment by alexander-vielimchanitsia** [comment]
In go-ipfs-api the error because of this import:
`manet "github.com/jbenet/go-multiaddr-net"`

**Comment by whyrusleeping** [comment]
@alexander-vielimchanitsia a way to get this working for you before I fix it (i'm working on it, its not an easy problem) is to change your imports in your code from "github.com/jbenet/go-multiaddr-net" to "gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net"

Let me know if that works and what errors you get if it doesnt

**Comment by alexander-vielimchanitsia** [comment]
@whyrusleeping changed https://github.com/ipfs/go-ipfs-api/blob/master/shell.go#L16 to 
`manet "gx/ipfs/QmYVqhVfbK4BKvbW88Lhm26b3ud14sTBvcm1H7uWUx1Fkp/go-multiaddr-net"`

then this errors:

# github.com/ipfs/go-ipfs-api
../../../../go/src/github.com/ipfs/go-ipfs-api/shell.go:29: cannot use a (type "github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr) as type "gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr in argument to manet.DialArgs:
	"github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr does not implement "gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr (wrong type for Decapsulate method)
		have Decapsulate("github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr) "github.com/jbenet/go-multiaddr-net/Godeps/_workspace/src/github.com/jbenet/go-multiaddr".Multiaddr
		want Decapsulate("gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr) "gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr

**Comment by whyrusleeping** [comment]
mmm.... thats a mess. Give me half an hour to play with this and i'll report back.

**Comment by whyrusleeping** [comment]
alright, so if you change the next line (the `go-multiaddr` one) to `"gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr"` it should solve that error.

**Comment by alexander-vielimchanitsia** [comment]
@whyrusleeping, yeah, thank you!

**Comment by lgierth** [comment]
I'm gonna close this one since we're not using UTP anymore in libp2p nor IPFS.
