### ISSUE TITLE
shell.Add always wraps a folder even only one file is added

### ISSUE THREAD

**Issue by CsterKuroi** [ipfs/go-ipfs-api#277]
This is a big overhead for systems that often add a single file when use go-ipfs-api.

**Comment by CsterKuroi** [comment]
https://github.com/ipfs/go-ipfs-api/blob/42a3388734299b72d7719a4f1b728d78e0a2e164/add.go#L65

**Comment by lidel** [comment]
We will not spend time on improving this library, let's continue in https://github.com/ipfs/kubo/issues/9124
