### ISSUE TITLE
Can ApiBase be set as custom? Make '/api/v0' optional.

### ISSUE THREAD

**Issue by jason-wj** [ipfs/go-ipfs-api#295]
In some cases, I need to use a custom URL to access private IPFS. The IPFS server has a gateway and will automatically add '/api/v0' to the link. Therefore, I hope that go-ipfs-api will not force 'ApiBase' to add `/api/v0`
[](url)
![WX20230530-161950@2x](https://github.com/ipfs/go-ipfs-api/assets/13200618/10e704ae-c3c7-469a-94ef-50129a932cc4)

**Comment by lidel** [comment]
@jason-wj  we are not actively  maintaining this library and it is unlikely we will add new features to it.
If you want, please open issue against [`kubo/client/rpc` library](https://github.com/ipfs/kubo/tree/master/client/rpc).
