### ISSUE TITLE
Archive this repo and point users at kubo/client/rpc

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs-api#296]
Placeholder issue so we don't forget, see details in https://github.com/ipfs/kubo/issues/9124.

TLDR: we want to maintain only one RPC client, it now lives in https://github.com/ipfs/kubo/tree/master/client/rpc.
In rare case the new library does not offer a feature this one does, fill issue in Kubo, or better, submit a PR that adds it to `kubo/client/rpc`.

**Comment by tgmtime** [comment]
Using terminal commands like this for such tasks provides more control, better performance, and reliability compared to using external libraries like the one you mentioned. Why would I prefer to use this library over working with terminal commands like: `cmd := exec.Command("ipfs", "get", cid)
output, err := cmd.CombinedOutput()
if err != nil {
    fmt.Println("Error running command:", err)
    return
}
`
