### ISSUE TITLE
pinning has opposite behaviour in webui with curl vs. shell

### ISSUE THREAD

**Issue by zramsay** [ipfs/go-ipfs-api#6]
Pinned file with curl shows up in "Files" -> "Pinned" (and not "Files" -> "All") whereas pinned file when using shell does the opposite. In both cases file is pinned successfully re: `ipfs pin ls`.

**Comment by whyrusleeping** [comment]
could you give us the curl command youre running and also the shell method youre calling?

**Comment by zramsay** [comment]
`curl "http://127.0.0.1:5001/api/v0/pin/add?arg=[someHash]` works as expected.

[This](https://github.com/eris-ltd/eris-cli/blob/91e2793708eae8f4917cb91fadc9241a40f6616d/util/writers.go#L23) is what I was doing pre-shell and also works as expected.

[Here](https://github.com/eris-ltd/eris-cli/blob/ipfs-refactor/util/writers.go#L40) is the shell code, which behaves as described.

The latter two are running through a `eris services` a docker container whereas the former is straight command line.

It may have something to do with the URL. The shell does some automagic formatting (like adding json encoding & stream octet) that I don't quite understand. Tried replicating the error with curl to no avail. Looks to be a strictly webui issue.

**Comment by jbenet** [comment]
@zramsay i believe the pinned tab in the webui isn't correct. @krl ?
