### ISSUE TITLE
PubSubSubscription receives empty message on subscription?

### ISSUE THREAD

**Issue by ktnyt** [ipfs/go-ipfs-api#66]
Hello I'm very new to IPFS and haven't had the time to dig into the code but I've been observing an odd but consistent behaviour where a call to the first `PubSubSubscription.Next()` immediately yields an empty `PubSubRecord` object. Here is a minimal example that replicates this phenomena on the two Macs I've tested it on:

```go
package main

import (
  "fmt"
  "log"

  "github.com/ipfs/go-ipfs-api"
)

func main() {
  ipfs := shell.NewShell("/ip4/127.0.0.1/tcp/5001")

  sub, err := ipfs.PubSubSubscribe("somerandomtopicthatijustmadeupforthispurpose")

  if err != nil {
    log.Fatal(err)
  }

  rec, err := sub.Next()

  if err != nil {
    log.Fatal(err)
  }

  fmt.Println(len(rec.Data()))
}
```

Is this intended and/or consistent behaviour? If it is consistent I can work around this but if it is not I might run into some issues.

**Comment by lgierth** [comment]
Yes that's expected on go-ipfs versions up to 0.4.13 -- master and the next release don't emit the empty message anymore. cc @keks

**Comment by ktnyt** [comment]
Thank you for the notice. I will keep an eye on the updates.
