### ISSUE TITLE
Difficult to add links to directory

### ISSUE THREAD

**Issue by samkumar** [ipfs/go-ipfs-api#67]
I'm new and trying out IPFS for the first time. I have a directory in IPFS that I've added from the command line using `ipfs add -r`. My objective is to write a go program that adds a file to that directory, and gives me the hash of the resulting directory. I can add the file to IPFS using the `Add` function, so all that's left to do is add the hash of the file to the directory as another link.

The trouble is that I can't find a way to do this efficiently using the API. I see an `AddDir` function, but ideally I don't want to have to download the entire directory tree, add my file, and then re-upload it, because the directory tree could be very large.

In terms of the Merkle DAG, what I want to do is create a copy of the object representing the directory, while adding an additional link. While there are functions that would let me do this in the API, it seems that they operate at the object level, and therefore do not correctly encode things to fit the filesystem abstraction (e.g., Size is not set correctly on links, bytes are not set correctly in the body of a directory, etc.)

I'm new to IPFS so it's possible I'm overlooking an obvious way to do this. Is there a way to add a new file to a directory without having to download the entire directory tree, using the go API? And if not, what are some workarounds I could use?

**Comment by lgierth** [comment]
You're looking for `ipfs object patch add-link --help`. It's available as `shell.Patch("/ipfs/QmBase", "add-link", "my-new-link", "/ipfs/QmDestination")`.

**Comment by samkumar** [comment]
@lgierth, thanks for your response! This works for me.
