### ISSUE TITLE
import conflict with floodsub

### ISSUE THREAD

**Issue by jvsteiner** [ipfs/go-ipfs-api#75]
I have a go-libp2p-floodsub based project in which I would also like to utilize a locally running ipfs node for various pieces of functionality related to content distribution, to avoid needing to reinvent large parts of ipfs.  However, it seems that this package cannot be used in the same project due to protobuf registrations issues.

With the following sample code:
```
package main

import (
	"fmt"

	_ "github.com/ipfs/go-ipfs-api"
	_ "github.com/libp2p/go-floodsub"
)

func main() {
	fmt.Println("Dear me...")
}
```
one can observe the following errors:
```
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.RPC
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.RPC.SubOpts
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.Message
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.TopicDescriptor
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.TopicDescriptor.AuthOpts
2018/03/12 12:40:41 proto: duplicate proto type registered: floodsub.pb.TopicDescriptor.EncOpts
panic: proto: duplicate enum registered: floodsub.pb.TopicDescriptor_AuthOpts_AuthMode
```
Seems like `go-ipfs-api` imports `go-libp2p-pubsub`  which is basically just a copy of the `go-floodsub` proto definitions.  I can work around this on a fork that substitutes the import statements if need be, but wondering if the way forward is really to use a non-canonical source for the proto definitions....

**Comment by Stebalien** [comment]
There was an attempt to extract the protobufs to `go-libp2p-pubsub` that was halted half way through, abandoned, but never reversed. @lgierth said this can be fixed but I'm not sure how he planned on doing that.

**Comment by jvsteiner** [comment]
I would imagine that the new lib would become a dependency of both `go-floodsub` and this.

**Comment by Stebalien** [comment]
See the discussion here: https://github.com/libp2p/go-floodsub/pull/61

**Comment by jvsteiner** [comment]
Leaving a note here as well - https://github.com/libp2p/go-libp2p-pubsub/issues/4#issuecomment-425626579 - Looks like the plan is not what I said above, instead it would be to depend on `go-floodsub`.

**Comment by Stebalien** [comment]
Fixed.
