### ISSUE TITLE
List(): json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by cryptix** [ipfs/go-ipfs-api#8]
The `Type` field of the json response is an int, not  string.

[repro code](https://gateway.ipfs.io/ipfs/QmUvyapTGXkBkgV8LGtLxhNmebnyqTvdu2SHqcAYk9oknc)

**Comment by jbenet** [comment]
is this fixed?

**Comment by cryptix** [comment]
Yup.
