### ISSUE TITLE
How to calculate CID of file data?

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs-api#84]
I'm currently trying to figure out how I can calculate the content hash of a file, without adding it to IPFS. I took a look at the code for the `Shell.Add` function, however it forwards the request onto ipfs itself, waiting for the returned response to retrieve the hash. What I'm attempting to do is calculate the hash of a file to be able to send that to a user, followed by uploading the hash to my ipfs node. The reason I want to caluclate the hash before uploading it to IPFS, is that this will be quicker to send them a response, instead of say having to wait for an entire 10GB file to be pinned to IPFS.

**Comment by magik6k** [comment]
`ipfs add` has `--only-hash` (or `-n`) option which calculates the hash. Currently there isn't a function exposing the option here, but it will be done as a part of https://github.com/ipfs/go-ipfs-api/pull/76.

There has been some discussion on this topic in https://discuss.ipfs.io/t/how-to-calculate-file-directory-hash/777

**Comment by postables** [comment]
Amazing. Thank you.
