### ISSUE TITLE
Is Shell.Pin recursive by default?

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipfs-api#85]
Took a look and I might be missing something but I can't seem to find a definitive answer as to whether or not `Shell.Pin` uses recursive pins by default. I see that here https://github.com/ipfs/go-ipfs-api/blob/d204576299ddab1140d043d0abb0d9b60a8a5af4/shell.go#L318 there is an enabling of the `r` option which I assume is recursive?

**Comment by magik6k** [comment]
Yes, `Shell.Pin` pins recursively.
