### ISSUE TITLE
General way to invoke all available commands with all options

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs-api#92]
It is very useful to have very clean go interfaces with nice typing. But right now the api is simply incomplete. We should have some fallback methods to be able to use any command and any option available, at the cost of complexity for the user.

For example, i want to use the trickledag layout, but i cannot call it because it hasn't been added to the nicer exported add commands. I don't see a way of doing it, and so instead i shelled out (gross). (yes, this should really just be contributed as we go, and we should source contributions this way, but the amount of time it takes to contribute this and bikeshed the interfaces is unreasonable for quick hacks).

I think that even as we work to a complete well-typed api, something like this should be possible:

```go
s, err := shell.AddWithAnyOpts(r, map[string]interface{}{
  "trickle": true,
  "chunker": "rabin-512-1024-2048",
})
```

and potentially something like this:

```go
func (s *shell) Cmd(cmd string, args []interface{}, opts map[string]interface{})

shell.Cmd("add", []interface{r}, map[string]interface{}{
  "trickle": true,
  "chunker": "rabin-512-1024-2048",
})
```

this would make it at worst case usable, instead of forcing us to shell out, or use js-api instead.

**Comment by jbenet** [comment]
(Something better/closer than `shell.NewRequest`)

**Comment by postables** [comment]
I've encountered this issue recently as well, and have ended up making some hacky wrappers to accomplish what I want to do.

If desired I'd be happy to cleanup my implementations add some tests and submit a PR. I'm heavily using `go-ipfs-api` right now and will be making my own modifications to accomodate missing functionality. If there's a list of commands, functions, etc... that are missing from `go-ipfs-api` I'll be happy to submit PRs if any of my modifications fix that.

**Comment by ninkisa** [comment]
This would be very useful. I wanted to use add with the option "nocopy" and currently this is not possible with go-ipfs-api

**Comment by Stebalien** [comment]
It now exists. You can use `shell.Request("add").Option("nocopy", true)...`
