### ISSUE TITLE
Any way to provide the key to use when publishing to IPNS?

### ISSUE THREAD

**Issue by soupdiver** [ipfs/go-ipfs-api#95]
I'm looking at https://github.com/ipfs/go-ipfs-api/blob/master/ipns.go#L9 and try to figure out _how_ to specify the key to use for publishing the record?
I can see that on the api side the value can be red in theory: https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/name.go#L42

I can implement that myself but I currently struggle to find the the point where https://github.com/ipfs/go-ipfs/blob/master/core/coreapi/name.go#L41 is invoked to see how the parameter needs to be formatted/named etc.

If someone can explain what I'm doing wrong or point me to the point where the http request is mapped to the `coreapi` function that would be awesome

**Comment by Stebalien** [comment]
I believe one was supposed to put the key's name/id in the "node" field. However, that won't work as implemented. This method looks a *bit* buggy.

**Comment by soupdiver** [comment]
I see...
As said I'm willing to help out with this, since I need this feature for a project I work on.
I tried to navigate myself through the code and figure out how/where the translation between http request and command invocation is done. But let's say that part of the code is not exactly easy to read/understand imho.

If I'm right I tracked it down to this location: https://github.com/ipfs/go-ipfs-cmds/blob/master/http/parse.go#L18 where the http request is parsed, matched against (sub)commands and arguments/options are set.

What I don't get is _how_ exactly this mapping is done.
Are the options/values red from the url? If yes, in which format do they need to be supplied? The only "example" I could find is this: https://github.com/ipfs/go-ipfs-cmds/blob/master/http/parse.go#L43

If you could clarify this a bit that would be great

**Comment by soupdiver** [comment]
ok I just figured that this would be solved when #91 is merged if I don't overlook something

**Comment by magik6k** [comment]
This package doesn't yet implement CoreAPI. This will be done in in #76, but that will take some time. Meanwhile #91 provides a good workaround

**Comment by soupdiver** [comment]
agree @magik6k

**Comment by postables** [comment]
#91 Should fix your issue. Before the PR is merged if you are in dire need of this functionality I have a forked `go-ipfs-api` branch https://github.com/RTradeLtd/go-ipfs-api

**Comment by soupdiver** [comment]
@postables thanks for the hint
Tt seems there is nothing that stops your PR from being merged anymore. So I maybe can avoid changing deps :)

**Comment by soupdiver** [comment]
@magik6k this can be closed since #91 merged now I guess?
