### ISSUE TITLE
No ability to send GET instead of POST requests?

### ISSUE THREAD

**Issue by bonedaddy** [ipfs/go-ipfs-api#99]
Hello, I'm currently working on a service for my project that requests content through public gateways. Initially when I wrote my module I was getting failures from every gateway due to read-only APIs not allowing POST requests which I found strange since I was making `cat` command requests which should be GET requests. After digging around the code I found that all requests made are actually sent as POST requests. https://github.com/ipfs/go-ipfs-api/blob/88adb78a7baeed60668cfc2a6b916942c4df6224/request.go#L77

Is there any way to make GET requests short of creating a new `Send` function that makes GET requests?

**Comment by Stebalien** [comment]
We should probably make the read-only API use POST requests. We should also enable CORS on the read-only API if exposed through the gateway.

See: https://github.com/ipfs/go-ipfs/issues/5223. Thoughts?

**Comment by postables** [comment]
100% agreed, especially your comment about not running a REST service.  A standard HTTP method (not sure if that's the right word) such as POST for all requests, would be very useful. You can then use CORS for more fine grained filtering over methods, etc...

**Comment by Stebalien** [comment]
This library now works with the read-only API as the read-only API now accepts POST requests. Please comment if this needs to be revisited for some reason or if og-ipfs-api _needs_ to allow GET requests.
